import React from 'react';
import { useGameStore } from '@/store/gameStore';
import { User, Award, Briefcase, Handshake, BrainCircuit, Star } from 'lucide-react';

export function CEOView() {
  const { player, allocateSkillPoint } = useGameStore();
  const profile = player.profile || { name: 'The Founder', age: 25, level: 1, xp: 0, reputation: 50, skillPoints: 0 };
  const skills = player.skills || { business: 1, investment: 1, negotiation: 1, leadership: 1 };

  const xpRequired = profile.level * 5000;
  const xpPercent = Math.min(100, Math.round((profile.xp / xpRequired) * 100));

  return (
    <div className="p-8 overflow-y-auto h-full space-y-10 relative z-10">
      
      {/* Header Profile Card */}
      <div className="bg-brand-card border border-brand-gold/30 rounded-2xl p-8 flex flex-col md:flex-row items-center space-y-6 md:space-y-0 md:space-x-8 shadow-xl relative overflow-hidden">
         <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-brand-gold to-brand-profit"></div>
         
         <div className="w-32 h-32 rounded-full bg-brand-surface border-4 border-brand-gold flex items-center justify-center shadow-[0_0_20px_rgba(245,196,81,0.3)]">
            <User size={64} className="text-brand-gold" />
         </div>

         <div className="flex-1 text-center md:text-left">
            <h2 className="text-4xl font-black text-brand-text mb-1">{typeof profile.name === 'string' ? profile.name : (profile.name as any)?.name || 'The Founder'}</h2>
            <p className="text-brand-muted text-lg font-medium tracking-wide mb-4">CEO & Founder • Age {typeof profile.name === 'string' ? profile.age : (profile.name as any)?.age || profile.age}</p>
            
            <div className="flex flex-col space-y-2 max-w-md">
               <div className="flex justify-between text-sm font-bold text-brand-text uppercase">
                  <span>Level {profile.level}</span>
                  <span className="text-brand-gold">{profile.xp.toLocaleString()} / {xpRequired.toLocaleString()} XP</span>
               </div>
               <div className="w-full bg-brand-bg rounded-full h-4 border border-black/10 overflow-hidden">
                  <div className="bg-brand-gold h-4 rounded-full transition-all" style={{ width: `${xpPercent}%` }}></div>
               </div>
            </div>
         </div>
         
         <div className="bg-brand-surface p-6 rounded-xl border border-black/10 text-center min-w-[150px]">
            <p className="text-brand-muted text-xs font-bold uppercase tracking-wider mb-1">Reputation</p>
            <p className="text-3xl font-black text-brand-blue">{profile.reputation} / 100</p>
         </div>
      </div>

      {/* Skills Tree */}
      <div>
         <div className="flex justify-between items-center mb-6 border-b border-black/10 pb-2">
            <h3 className="text-2xl font-bold text-brand-text flex items-center">
               <BrainCircuit className="mr-3 text-brand-blue" /> Executive Skill Tree
            </h3>
            {profile.skillPoints > 0 && (
               <div className="bg-brand-profit/20 text-brand-profit px-4 py-2 rounded-lg font-bold animate-pulse flex items-center">
                  <Star size={16} className="mr-2" /> {profile.skillPoints} Skill Points Available
               </div>
            )}
         </div>

         <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <SkillCard 
               title="Business Strategy" icon={<Briefcase size={24} />} level={skills.business} 
               description="Reduces operating expenses (COGS & Payroll) across all owned businesses by 2% per level."
               onUpgrade={() => allocateSkillPoint('business')} canUpgrade={profile.skillPoints > 0 && skills.business < 10}
            />
            <SkillCard 
               title="Investment Acumen" icon={<Star size={24} />} level={skills.investment} 
               description="Increases passive income from all investments (Dividends, Bonds, Rent) by 5% per level."
               onUpgrade={() => allocateSkillPoint('investment')} canUpgrade={profile.skillPoints > 0 && skills.investment < 10}
            />
            <SkillCard 
               title="Negotiation" icon={<Handshake size={24} />} level={skills.negotiation} 
               description="Reduces the purchase price of assets and companies during acquisitions."
               onUpgrade={() => allocateSkillPoint('negotiation')} canUpgrade={profile.skillPoints > 0 && skills.negotiation < 10}
            />
            <SkillCard 
               title="Leadership" icon={<User size={24} />} level={skills.leadership} 
               description="Increases the revenue generated by all owned businesses by 5% per level."
               onUpgrade={() => allocateSkillPoint('leadership')} canUpgrade={profile.skillPoints > 0 && skills.leadership < 10}
            />
         </div>
      </div>
    </div>
  );
}

function SkillCard({ title, icon, level, description, onUpgrade, canUpgrade }: { title: string, icon: React.ReactNode, level: number, description: string, onUpgrade: () => void, canUpgrade: boolean }) {
   return (
      <div className="bg-brand-surface border border-black/10 p-6 rounded-xl flex flex-col justify-between">
         <div>
            <div className="flex justify-between items-center mb-4">
               <div className="flex items-center space-x-3 text-brand-text font-bold text-lg">
                  <div className="text-brand-blue">{icon}</div>
                  <span>{title}</span>
               </div>
               <div className="bg-brand-bg px-3 py-1 rounded border border-black/10 font-mono font-bold text-brand-text">
                  Lvl {level}/10
               </div>
            </div>
            <p className="text-brand-muted text-sm mb-6">{description}</p>
         </div>
         
         <button 
            onClick={onUpgrade}
            disabled={!canUpgrade}
            className={`w-full py-3 rounded-lg font-bold text-sm transition-all ${canUpgrade ? 'bg-brand-blue text-white hover:bg-blue-600 shadow-lg' : 'bg-brand-bg text-brand-muted cursor-not-allowed border border-black/10'}`}
         >
            {level >= 10 ? 'MAX LEVEL' : canUpgrade ? 'UPGRADE SKILL' : 'NOT ENOUGH SKILL POINTS'}
         </button>
      </div>
   );
}
